// Make image asset imports (*.webp, *.svg, *.png, *.avif) type-check.
//
// next-env.d.ts already pulls these in via next/image-types/global, but that
// file is git-ignored (it's generated by `next dev` / `next build`) and so is
// absent in CI, where we run a bare `tsc --noEmit`. This committed reference
// restores the ambient module declarations without depending on any generated
// file (unlike next-env.d.ts, which also imports generated route types).
/// <reference types="next/image-types/global" />
