import type { LocationData } from '@/app/ui/components/LocationCard/location-card';

export const locationsData: LocationData[] = [
  {
    id: 'location-1',
    name: 'Miami – South (US-1)',
    address: '18200 S Dixie Hwy, Miami, FL 33157',
    locationStore: 'Serving Cutler Bay • Palmetto Bay • South Miami • Kendall • Pinecrest',
    phone: '(305)-278-4632',
    backgroundImage: '/assets/images/Locations/18200.jpg',
    link: 'https://maps.app.goo.gl/RTpygmaN6vMcPxmX8',
  },
  {
    id: 'location-2',
    name: 'Miami – Airport',
    address: '3251 NW 27th Ave, Miami, FL 33142',
    locationStore: 'Serving Allapattah • Midtown • Near Miami Int’l Airport',
    phone: '(305)-456-9588',
    backgroundImage: '/assets/images/Locations/3251.webp',
    link: 'https://maps.app.goo.gl/1gpRJFveeqs3hM7G9',
  },
  {
    id: 'location-3',
    name: 'Miami – North (441)',
    address: '20282 NW 2nd Ave, Miami, FL 33169',
    locationStore: 'Serving Miami Gardens • Hollywood • Aventura',
    phone: '(305)-770-1154',
    backgroundImage: '/assets/images/Locations/20282.jpg',
    link: 'https://maps.app.goo.gl/G79tY9zNu7ETtru8A',
  },
  {
    id: 'location-4',
    name: 'Miami – Coral Gables',
    address: '900 South Le Jeune Rd, Miami, FL 33134',
    locationStore: 'Serving Coral Gables • Westchester • Near MIA Airport',
    phone: '(305)-713-1258',
    backgroundImage: '/assets/images/Locations/900.jpg',
    link: 'https://maps.app.goo.gl/99HuCuuroqTVZRdz8',
  },
  {
    id: 'location-5',
    name: 'Miami – Hialeah',
    address: '4040 E 10th Ct, Hialeah, FL 33013',
    locationStore: 'Serving Hialeah • Miami Springs • East Hialeah',
    phone: '(305)-836-4200',
    backgroundImage: '/assets/images/Locations/4040.webp',
    link: 'https://maps.app.goo.gl/oF6vhCsS7MdikcYX8',
  },
  {
    id: 'location-6',
    name: 'Orlando – West Colonial',
    address: '4400 W Colonial Dr, Orlando, FL 32808',
    locationStore: 'Serving Midtown • Wintergarden • West Orlando',
    phone: '(407)-203-3912',
    backgroundImage: '/assets/images/Locations/4400.jpg',
    link: 'https://maps.app.goo.gl/n32Upo4RiH9PWJVA7',
  },
  {
    id: 'location-7',
    name: 'Orlando – Semoran',
    address: '575 N Semoran Blvd, Orlando, FL 32807',
    locationStore: "Serving Azalea Park • Winter Park • East Orlando • Near Orlando Int'l Airport",
    phone: '(407)-282-3100',
    backgroundImage: '/assets/images/Locations/575.jpg',
    link: 'https://maps.app.goo.gl/fuDXk1EAKZ5ZAvpu6',
  },
];
